version: "3.7"

networks:
  python_package_template_network:

services:

  python_package_template:
    image: aguliyev/python_package_template:${IMAGE_VERSION}
    container_name: python_package_template
    build:
      context: .
      dockerfile: package.Dockerfile
      args:
        - ENV_NAME
        - PIP_PARAMS
        - AWS_CODEARTIFACT_AUTH_TOKEN
    networks:
      - python_package_template_network
    volumes:
      - type: bind
        source: .
        target: /app
    env_file:
      - etc/${ENV_NAME}/.env

  python_package_template_jupyter:
    image: aguliyev/python_package_template_jupyter
    container_name: python_package_template_jupyter
    build:
      context: .
      dockerfile: jupyter.Dockerfile
      args:
        - ENV_NAME
        - PIP_PARAMS
        - AWS_CODEARTIFACT_AUTH_TOKEN
    ports:
      - ${JUPYTER_PORT_ON_HOST}:${JUPYTER_PORT}
    networks:
      - python_package_template_network
    volumes:
      - ./docs/notebooks:/home/jovyan/work/notebooks
      - .:/home/jovyan/python_package_template
      - ./tmp:/tmp
    environment:
      - ENV_NAME
      - JUPYTER_ENABLE_LAB
      - JUPYTER_TOKEN
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
